export const baseUrl =
  import.meta.env.MODE === "production"
    ? "https://smart-gift-planner-backend.onrender.com"
    : "http://localhost:3002";

// export const recipients = [
//   {
//     _id: 1,
//     name: "Mike",
//     group: "Family",
//     priceRange: "300",
//     categories: ["Shoes"],
//     products: [1],
//   },
//   {
//     _id: 2,
//     name: "Sam",
//     group: "Friend",
//     priceRange: "80",
//     categories: ["Accessories"],
//     products: [2],
//   },
//   {
//     _id: 3,
//     name: "Charlie",
//     group: "Family",
//     priceRange: "250",
//     categories: ["Outerwear"],
//     products: [3],
//   },
//   {
//     _id: 4,
//     name: "Katie",
//     group: "Friend",
//     priceRange: "70",
//     categories: ["Shirts"],
//     products: [15],
//   },
//   {
//     _id: 5,
//     name: "Lee",
//     group: "Co-worker",
//     priceRange: "50",
//     categories: ["Accessories"],
//     products: [10],
//   },
// ];

export const testItems = [
  {
    _id: 1,
    name: "Boot",
    price: 59.99,
    description: "Winter boot",
    broad_category: "Sports",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Boot.png?etag=0953a2ea59f1c6ebc832fabacdc9c70e",
    isLiked: false,
  },
  {
    _id: 2,
    name: "Cap",
    price: 25.99,
    description: "Summer cap",
    broad_category: "Sports & Outdoors",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Cap.png?etag=f3dad389b22909cafa73cff9f9a3d591",
    isLiked: false,
  },
  {
    _id: 3,
    name: "Coat",
    price: 219.99,
    description: "Winter Coat",
    broad_category: "Health",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Coat.png?etag=298717ed89d5e40b1954a1831ae0bdd4",
    isLiked: false,
  },
  {
    _id: 4,
    name: "Dress",
    price: 159.99,
    description: "Summer dress",
    broad_category: "Beauty",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Dress.png?etag=1f9cd32a311ab139cab43494883720bf",
    isLiked: false,
  },
  {
    _id: 5,
    name: "Hoodie",
    price: 92.99,
    description: "Winter Hoodie",
    broad_category: "Automotive",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Hoodie.png?etag=5f52451d0958ccb1016c78a45603a4e8",
    isLiked: false,
  },
  {
    _id: 6,
    name: "Jacket",
    price: 199.99,
    description: "Winter Jacket",
    broad_category: "Automotive",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Jacket.png?etag=f4bb188deaa25ac84ce2338be2d404ad",
    isLiked: false,
  },
  {
    _id: 7,
    name: "Jeans",
    price: 99.99,
    description: "Winter Jeans",
    broad_category: "Electronics",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Jeans.png?etag=58345e8bef1ce5f95ac882e71d309e6c",
    isLiked: false,
  },
  {
    _id: 8,
    name: "Loafers",
    price: 15.99,
    description: "Winter Loafers",
    broad_category: "Home Appliances",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Loafers.png?etag=dc2d6e1ca7b297597406e35c40aef030",
    isLiked: false,
  },
  {
    _id: 9,
    name: "Sandals",
    price: 20.99,
    description: "Summer Sandals",
    broad_category: "Party Supplies",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Sandals.png?etag=9bea85a77c0306586d2b71a33b626d41",
    isLiked: false,
  },
  {
    _id: 10,
    name: "Scarf",
    price: 14.99,
    description: "Winter Scarf",
    broad_category: "Smart Home",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Scarf.png?etag=74efbee93810c926b5507e862c6cb76c",
    isLiked: false,
  },
  {
    _id: 11,
    name: "Shorts",
    price: 45.99,
    description: "Summer shorts",
    broad_category: "Gift Cards",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Shorts.png?etag=d728c496643f610de8d8fea92dd915ba",
    isLiked: false,
  },
  {
    _id: 12,
    name: "Skirt",
    price: 139.99,
    description: "Summer skirt",
    broad_category: "Pet Supplies",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Skirt.png?etag=27a6bea7e1b63218820d615876fa31d1",
    isLiked: false,
  },
  {
    _id: 13,
    name: "Sneakers",
    price: 89.99,
    description: "Home",
    broad_category: "Home & Kitchen",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Sneakers.png?etag=3efeec41c1c78b8afe26859ca7fa7b6f",
    isLiked: false,
  },
  {
    _id: 14,
    name: "Sunglasses",
    price: 99.99,
    description: "Summer Sunglasses",
    broad_category: "Industrial",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Sunglasses.png?etag=a1bced9e331d36cb278c45df51150432",
    isLiked: false,
  },
  {
    _id: 15,
    name: "Sweatshirt",
    price: 53.99,
    description: "Summer Sweatshirt",
    broad_category: "Baby",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/Sweatshirt.png?etag=008a9674757bea2e0bdb31242e364be0",
    isLiked: false,
  },
  {
    _id: 16,
    name: "T-Shirt",
    price: 37.99,
    description: "Summer T-shirt",
    broad_category: "Travel",
    link: "https://practicum-content.s3.us-west-1.amazonaws.com/software-engineer/wtwr-project/T-Shirt.png?etag=44ed1963c44ab19cd2f5011522c5fc09",
    isLiked: false,
  },
];

export const catregoryOptions = [
  {
    id: 0,
    label: "Travel",
    value: "Travel",
  },
  {
    id: 1,
    label: "Clothing",
    value: "Clothing",
  },
  {
    id: 2,
    label: "Electronics",
    value: "Electronics",
  },
  {
    id: 3,
    label: "Home",
    value: "Home",
  },
  {
    id: 4,
    label: "Smart Home",
    value: "Smart Home",
  },
  {
    id: 5,
    label: "Home Appliances",
    value: "Home Appliances",
  },
  {
    id: 6,
    label: "Home & Kitchen",
    value: "Home & Kitchen",
  },
  {
    id: 7,
    label: "Baby",
    value: "Baby",
  },
  {
    id: 8,
    label: "Industrial",
    value: "Industrial",
  },
  {
    id: 9,
    label: "Automotive",
    value: "Automotive",
  },
  {
    id: 10,
    label: "Beauty",
    value: "Beauty",
  },
  {
    id: 11,
    label: "Arts & Crafts",
    value: "Arts & Crafts",
  },
  {
    id: 12,
    label: "Pet Supplies",
    value: "Pet Supplies",
  },
  {
    id: 13,
    label: "Party Supplies",
    value: "Party Supplies",
  },
  {
    id: 14,
    label: "Health",
    value: "Health",
  },
  {
    id: 15,
    label: "Smart Devices",
    value: "Smart Devices",
  },
  {
    id: 16,
    label: "Education",
    value: "Education",
  },
  {
    id: 17,
    label: "Sports",
    value: "Sports",
  },
  {
    id: 18,
    label: "Sports & Outdoors",
    value: "Sports & Outdoors",
  },
  {
    id: 19,
    label: "Gift Cards",
    value: "Gift Cards",
  },
];

export const groupOptions = [
  { label: "Relationship...", value: "empty" },
  { label: "Family", value: "Family" },
  { label: "Friends", value: "Friends" },
  { label: "Co-workers", value: "Co-workers" },
  { label: "Other", value: "Other" },
];
